name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0'
        include-prerelease: True
    - name: Restore dependencies
      run: dotnet restore Snakes.sln
    - name: Build
      run: dotnet build --no-restore Snakes.sln
    - name: Test
      run: dotnet test Snakes.sln --no-build --verbosity normal
