name: Build container images

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build 'snakessilo' image
        uses: docker/build-push-action@v2
        with:
          push: false
          file: ./SnakesSilo/Dockerfile

      - name: Build 'sneks-hub' image
        uses: docker/build-push-action@v2
        with:
          push: false
          file: ./HubAndHost/Dockerfile
