name: Build and deploy images to Azure Container Apps

on:
  push:
    branches:
      [ main ]

  # Allow mannually trigger
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: snekscr.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and push 'snakessilo' image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: snekscr.azurecr.io/sneks-silo:${{ github.sha }}
          file: ./SnakesSilo/Dockerfile
          build-args: GIT_SHA=${{ github.sha }}

      - name: Build and push 'sneks-hub' image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: snekscr.azurecr.io/sneks-hub:${{ github.sha }}
          file: ./HubAndHost/Dockerfile
          build-args: GIT_SHA=${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploying 'sneks-silo' and 'sneks-hub' to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            echo "Installing containerapp extension"
            az extension add --name containerapp --yes
            echo "Setting registry for 'sneks-silo'"
            az containerapp registry set -n sneks-silo -g sneks-rg --server snekscr.azurecr.io --username  ${{ secrets.REGISTRY_USERNAME }} --password ${{ secrets.REGISTRY_PASSWORD }} --debug
            echo "Starting Deploying 'sneks-silo'"
            az containerapp update -n sneks-silo -g sneks-rg --image snekscr.azurecr.io/sneks-silo:${{ github.sha }}
            echo "Setting registry for 'sneks-hub'"
            az containerapp registry set -n sneks-hub -g sneks-rg --server snekscr.azurecr.io --username  ${{ secrets.REGISTRY_USERNAME }} --password ${{ secrets.REGISTRY_PASSWORD }} --debug
            echo "Starting Deploying 'sneks-hub'"
            az containerapp update -n sneks-hub -g sneks-rg --image snekscr.azurecr.io/sneks-hub:${{ github.sha }}
